title: "Práctica 1 - Configuración de Máquina Virtual en el IaaS de la ULL"
description: "Informe sobre la configuración de una máquina virtual en el Servicio IaaS de la ULL, incluyendo la instalación de herramientas esenciales y la integración con GitHub."
author: "Alfredo Moreno Mondragón"
email: "alu0101515601@ull.edu.es"

# Configuración de Markdown
highlighter: rouge

# Formato de fecha
# date_format: "%d-%m-%Y"

remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
