title: "Práctica 1 - Configuración de Máquina Virtual en el IaaS de la ULL"
description: "Informe sobre la configuración de una máquina virtual en el Servicio IaaS de la ULL, incluyendo la instalación de herramientas esenciales y la integración con GitHub."
author: "Alfredo Moreno Mondragón"
email: "alu0101515601@ull.edu.es"

remote_theme: alu0101515601@ull.edu.es
plugins:
- jekyll-remote-theme

highlighter: rouge  
