# Configuración básica del sitio
title: "Informe Práctica 01 DSI"
description: "Configuración de Máquina Virtual en el IaaS"
author: "Francisco Fdez"
email: "alu0101427324@ull.edu.es"
url: "https://ffdezgomez-p01-dsi.github.io"  # URL de tu sitio en GitHub Pages

# Selección del tema (elige uno de la lista oficial de GitHub Pages)
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Configuración para Markdown
highlighter: rouge  # Resaltador de sintaxis para código
